version: '3'

services:
  pgsql:
    image: postgres:9.6
    container_name: pgsql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pg-user
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=coffee
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    # networks:
    #   - pgsql
    restart: always
    # depends_on:
    #   - redis
